spring:
  application:
    name: git-jenkins-integration

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 5000

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always